from pathlib import Path
import json
from textwrap import dedent

ROOT = Path(r"C:\Users\samlu\.openclaw\workspace")
APP = ROOT / "applications"
AUDITS = ROOT / "application_audits"
PREFIX = "2026-08-12"
APP.mkdir(exist_ok=True)
AUDITS.mkdir(exist_ok=True)

common_review = [
    "Check the listing date, closing date, location, roster, and application route.",
    "Read the tailored documents once and edit any wording that doesn’t sound like you.",
    "Confirm every licence, qualification, clearance, vehicle, and work-right requirement.",
    "Submit manually only after your explicit approval."
]

roles = [
 {"lane":"core","slug":"Crown_Senior_Cloud_Infrastructure_Engineer","company":"Crown Resorts","title":"Senior Cloud and Infrastructure Engineer","location":"Melbourne, VIC","posted":"2026-08-11","url":"https://au.indeed.com/viewjob?jk=8634cd363eaca011","score":92,"remote":False,"why":"Strong cloud and infrastructure match: Azure, hybrid identity, enterprise operations, automation, incident ownership, and regulated-service delivery.","terms":["Cloud infrastructure","Azure","enterprise operations","incident management","automation","security"],"gaps":["Confirm the cloud platform mix, on-call expectations, and any casino-industry compliance requirement."],"summary":"Senior infrastructure and Microsoft 365 engineer with Azure, hybrid identity, enterprise operations, PowerShell automation, and Tier-3 incident experience. Delivers durable cloud and infrastructure improvements in complex, service-critical environments.","profile":"This role closely matches my background in Azure adoption, infrastructure operations, hybrid identity, security-aware change, automation, and operational ownership across government, healthcare, and enterprise environments.","skills":"Azure · Microsoft 365 · Entra ID · hybrid identity · Windows Server · Active Directory · PowerShell · Azure DevOps · incident and problem management · RCA · security baselines · ServiceNow · technical documentation","focus":"cloud"},
 {"lane":"core","slug":"Oasis_System_Administrator","company":"Oasis Services Australia Pty Ltd","title":"System Administrator","location":"Preston, VIC · remote work available","posted":"2026-08-10","url":"https://au.indeed.com/viewjob?jk=a34c49df9122c9ec","score":90,"remote":True,"why":"Direct systems-administration fit: identity, endpoint and server support, patching, backups, access, incident response, documentation, and practical operations.","terms":["Systems administration","user access","device support","backups","patching","infrastructure"],"gaps":["Confirm backup platform, server estate, on-call requirements, and any care-sector screening requirement."],"summary":"Systems administrator and Microsoft 365 engineer with practical ownership of identity, Windows endpoints, infrastructure support, patching, automation, incident resolution, and service documentation.","profile":"I bring hands-on administration across enterprise user access, Windows and endpoint lifecycle, hybrid identity, troubleshooting, patching, automation, and operational documentation.","skills":"Windows Server · Active Directory · Entra ID · Microsoft 365 · Intune · Windows 10/11 · PowerShell · backup and recovery · patching · DNS · DHCP · ServiceNow · incident management","focus":"systems"},
 {"lane":"core","slug":"KBR_Senior_IT_Systems_Administrator","company":"KBR","title":"Senior IT Systems Administrator","location":"Melbourne, VIC","posted":"2026-08-10","url":"https://au.indeed.com/viewjob?jk=6f94d83452edef46","score":91,"remote":False,"why":"Strong senior systems-administration match across Windows Server, Active Directory, hybrid identity, enterprise support, automation, security, and documented operations.","terms":["IT systems administration","Windows Server","Active Directory","infrastructure","security","technical support"],"gaps":["Confirm citizenship, defence-security-clearance eligibility, on-site requirements, and the exact server and networking stack."],"summary":"Senior systems and Microsoft 365 engineer experienced in Windows Server, Active Directory, Entra ID, Azure, enterprise support, PowerShell automation, security-aware operations, and Tier-3 escalation.","profile":"This role is a strong fit for my systems-administration, hybrid identity, cloud, service-operations, documentation, and security-baseline experience in large government and enterprise settings.","skills":"Windows Server · Active Directory · Entra ID · Azure · Microsoft 365 · DNS · DHCP · Group Policy · PowerShell · ServiceNow · ITIL 4 · RCA · Essential 8 · technical documentation","focus":"systems"},
 {"lane":"core","slug":"Epicor_Cloud_R_Analyst","company":"Epicor Software","title":"Cloud R Analyst","location":"Melbourne, VIC","posted":"2026-08-11","url":"https://au.indeed.com/viewjob?jk=d8ce82c4d5bc1147","score":85,"remote":False,"why":"Good Tier-2 cloud-operations match: triage across application, database, network, and infrastructure teams, with incident ownership and practical RCA.","terms":["Tier 2 incidents","cloud-hosted applications","infrastructure","application support","triage","incident resolution"],"gaps":["Confirm Epicor product exposure, Linux or database expectations, support roster, and customer-facing escalation model."],"summary":"Cloud and application-support engineer with Tier-3 escalation experience across Azure, Windows Server, SQL, APIs, enterprise SaaS, incident triage, and root-cause analysis.","profile":"I bring practical cloud-operations experience spanning complex incident ownership, cross-team triage, automation, application support, documented RCA, and durable preventive fixes.","skills":"Cloud operations · Azure · Windows Server · SQL · REST APIs · application support · incident triage · RCA · PowerShell · Python · ServiceNow · SLA management · technical documentation","focus":"cloud"},
 {"lane":"technician","slug":"Westbourne_ICT_Technician_Level_2","company":"Westbourne Grammar School","title":"ICT Technician Level 2","location":"Truganina, VIC","posted":"2026-08-12","url":"https://au.indeed.com/viewjob?jk=3c833e97aeabae3c","score":89,"remote":False,"why":"Excellent endpoint and school-technology fit: Level 2 support, Windows, device lifecycle, Microsoft 365, troubleshooting, documentation, and education-sector context.","terms":["Level 2 support","ICT support","Windows","Microsoft 365","endpoint management","troubleshooting"],"gaps":["Confirm Working with Children Check requirement, campus travel, device fleet, and exact closing date of 26 August 2026."],"summary":"Endpoint and ICT support engineer with Level 2/3 troubleshooting, Windows 10/11, Intune, Autopilot, Microsoft 365, hardware lifecycle, documentation, and education-sector experience.","profile":"This role strongly aligns with my hands-on endpoint support, device provisioning, Windows migration, Microsoft 365 administration, user communication, and experience supporting the Victorian education environment.","skills":"Level 2 support · Windows 10/11 · Intune · Autopilot · Microsoft 365 · Entra ID · hardware diagnostics · imaging · endpoint lifecycle · ServiceNow · technical documentation · stakeholder support","focus":"endpoint"},
 {"lane":"technician","slug":"MedHealth_Desktop_Support_Technician","company":"MedHealth","title":"Desktop Support Technician","location":"Melbourne, VIC","posted":"2026-08-12","url":"https://au.indeed.com/viewjob?jk=abf57f0480b18fc1","score":90,"remote":False,"why":"Strong desktop-support match: enterprise endpoint troubleshooting, Windows migrations, provisioning, Intune, user support, asset management, and healthcare delivery experience.","terms":["Desktop support","Windows","hardware support","endpoint management","user support","troubleshooting"],"gaps":["Confirm travel between sites, roster, imaging and endpoint tooling, and any health-sector screening requirement."],"summary":"Desktop and endpoint support engineer with enterprise Windows support, hardware diagnostics, Intune, Autopilot, imaging, lifecycle management, user support, and healthcare migration experience.","profile":"I bring practical desktop support across endpoint provisioning, break-fix, Windows 10/11 migration, inventory, standard operating environments, Intune policy validation, and user handover.","skills":"Desktop support · Windows 10/11 · Intune · Autopilot · hardware diagnostics · imaging · endpoint lifecycle · Microsoft 365 · ServiceNow · inventory management · user support · RCA","focus":"endpoint"},
 {"lane":"technician","slug":"Comwire_L1_Helpdesk_Technician","company":"Comwire IT","title":"L1 Helpdesk Technician (VIC)","location":"Prahran, VIC · remote work available","posted":"2026-08-12","url":"https://au.indeed.com/viewjob?jk=3df1040fbb536ffd","score":87,"remote":True,"why":"Strong service-desk and MSP fit: L1 support, remote troubleshooting, Windows and Microsoft 365, ServiceNow, SLA discipline, customer communication, and escalation judgement.","terms":["L1 helpdesk","technical assistance","hardware","software","network issues","end-user support"],"gaps":["Confirm shift coverage, customer-site travel, call volume, remote-work arrangements, and any MSP tooling not shown in the listing."],"summary":"IT support engineer with high-volume L1/L2 service-desk delivery, Windows and Microsoft 365 troubleshooting, ServiceNow automation, endpoint lifecycle, user communication, and reliable escalation management.","profile":"This role matches my practical experience supporting end users by phone, remote tools, and face-to-face engagement while resolving hardware, software, access, and connectivity issues within SLA.","skills":"L1/L2 support · Windows 10/11 · Microsoft 365 · Entra ID · Active Directory · ServiceNow · remote support · hardware diagnostics · networking fundamentals · incident management · SLA delivery · documentation","focus":"endpoint"},
 {"lane":"technician","slug":"OZCOM_Technical_Support_Officer_Education","company":"OZCOM TECHNOLOGY GROUP","title":"Technical Support Officer - Education","location":"Melton, VIC","posted":"2026-08-10","url":"https://au.indeed.com/viewjob?jk=621c8cf356ccfff4","score":86,"remote":False,"why":"Good education-technology support fit: onsite ICT support, managed-school services, endpoint troubleshooting, user communication, documentation, and Victorian education experience.","terms":["Technical support","education","onsite support","ICT services","school","end-user support"],"gaps":["Confirm Working with Children Check, contract duration, travel, school holiday coverage, and the managed-service toolset."],"summary":"Technical support and endpoint engineer with onsite and remote ICT support, Windows 10/11, Intune, Autopilot, Microsoft 365, hardware lifecycle, and government-education experience.","profile":"I bring practical managed-service discipline plus direct familiarity with education-sector systems, end-user support, endpoint provisioning, troubleshooting, documentation, and stakeholder communication.","skills":"Technical support · education ICT · Windows 10/11 · Microsoft 365 · Intune · Autopilot · hardware diagnostics · Active Directory · remote support · onsite support · ServiceNow · documentation","focus":"endpoint"},
 {"lane":"technician","slug":"STACK_Critical_Operations_Technician_Electrical","company":"STACK Infrastructure APAC","title":"Critical Operations Technician - Electrical (Australia)","location":"Melbourne, VIC","posted":"2026-08-12","url":"https://au.indeed.com/viewjob?jk=4b96c6a91526b9bd","score":83,"remote":False,"why":"Relevant data-centre and critical-environment foundation: physical infrastructure, HVAC, cabling, systematic fault-finding, equipment handling, operations discipline, and technical documentation.","terms":["Critical operations","data centers","electrical","facility operations","maintenance","safety"],"gaps":["Electrical licence, HV switching authority, critical-facility experience, roster, safety certifications, and on-call requirements require confirmation."],"summary":"Infrastructure support engineer with hands-on data-centre-adjacent experience in structured cabling, hardware deployment, HVAC service, systematic fault-finding, operational documentation, and enterprise technical support.","profile":"This role is a practical adjacent match: I bring physical infrastructure, facilities-awareness, hardware troubleshooting, data-centre thermal-management understanding, structured cabling, and disciplined service operations. Electrical credentials must be confirmed before applying.","skills":"Data centre fundamentals · structured cabling · fibre and copper · HVAC service · hardware troubleshooting · facilities awareness · environmental controls · safety-conscious work · incident documentation · customer communication","focus":"field"},
 {"lane":"outdoor","slug":"Glen_Eira_Crew_Member_Open_Space_Assets","company":"Glen Eira City Council","title":"Crew Member - Open Space Assets","location":"Caulfield, VIC","posted":"2026-08-11","url":"https://au.indeed.com/viewjob?jk=317d5f97311eaa91","score":78,"remote":False,"why":"Practical nearby council pathway with field-service discipline, physical infrastructure work, safe work practices, fault-finding, documentation, and customer communication.","terms":["Open space assets","parks services","maintenance","full-time","council","safety"],"gaps":["Confirm mandatory licences, outdoor-maintenance qualifications, physical requirements, roster, and closing date of 19 August 2026."],"summary":"Field-service and technical support professional with hands-on installation, maintenance, fault-finding, work-order discipline, customer communication, and safety-conscious operations experience across Melbourne.","profile":"This role offers a practical local pathway where my field infrastructure, HVAC service, physical fault-finding, site assessment, documentation, and dependable work ownership are directly relevant. Role-specific parks skills and licences need confirmation.","skills":"Field service · maintenance · fault-finding · site assessment · equipment handling · work orders · safety-conscious operations · customer service · documentation · team collaboration","focus":"field"},
 {"lane":"local","slug":"Max_Brenner_Cafe_Supervisor","company":"Max Brenner","title":"Café Supervisor","location":"Melbourne, VIC","posted":"2026-08-12","url":"https://au.indeed.com/viewjob?jk=0ab58f8334bb9d3e","score":72,"remote":False,"why":"Part-time practical role; transferability rests on customer communication, prioritisation, dependable shift work, inventory experience, and operational discipline rather than direct café experience.","terms":["Café supervisor","part-time","customer service","team support","retail","food service"],"gaps":["Direct café leadership, food-handling certification, availability, late-trading roster, and prior hospitality requirements require confirmation."],"summary":"Customer-focused operations professional with frontline support, inventory coordination, team communication, prioritisation under pressure, and reliable service delivery in high-volume environments.","profile":"This is a practical part-time pathway. My direct experience is in customer-facing technical operations rather than hospitality, but I bring fast-paced service delivery, stock handling, clear communication, shift discipline, and a willingness to complete any required food-safety training.","skills":"Customer service · team support · shift prioritisation · inventory coordination · issue resolution · clear communication · process discipline · safety awareness · reliable attendance","focus":"local"},
 {"lane":"local","slug":"Lindt_Retail_Store_Team_Member","company":"Lindt & Sprüngli (Australia) Pty Ltd","title":"Retail Store Team Member","location":"South Wharf, VIC","posted":"2026-08-10","url":"https://au.indeed.com/viewjob?jk=f918964674f63cbf","score":70,"remote":False,"why":"Practical local retail pathway; customer service, product support, inventory, team collaboration, reliability, and clear communication transfer well, while direct retail experience should be confirmed.","terms":["Retail store","team member","customer service","product knowledge","sales","store operations"],"gaps":["Direct retail-sales history, availability, weekend roster, cash handling, and food-safety requirements require confirmation."],"summary":"Customer-focused operations professional with high-volume support, inventory coordination, practical problem-solving, clear communication, and dependable team delivery in service-driven environments.","profile":"This role is a practical local option. While my background is technical operations rather than retail, I bring customer-facing service, accurate process execution, stock and asset awareness, teamwork, and a willingness to learn product and point-of-sale processes.","skills":"Customer service · teamwork · stock and asset handling · process accuracy · issue resolution · communication · shift reliability · safety awareness · operational support","focus":"local"}
]

experience = {
 "cloud": [
 ("Senior Managed Services Engineer — Capgemini, consultant to Department of Education Victoria", "December 2021–2023 · Melbourne, Victoria", ["Managed Azure, SharePoint Online, Exchange Online, Teams, Entra ID, hybrid identity, and Google Workspace in a government environment supporting 660,000+ users.", "Acted as a Tier-3 escalation point, led root-cause analysis, and introduced preventive fixes that reduced repeat incidents by 15 percent.", "Supported Azure adoption, legacy remediation, Essential 8-aligned security baselines, identity synchronisation, and operational runbooks."]),
 ("Application Support Engineer — Knosys", "December 2020–December 2021 · Melbourne, Victoria", ["Provided L3 support for enterprise SaaS, resolving SQL, API, authentication, browser, and Windows Server issues within SLA.", "Built PowerShell automation that reduced migration processing time by 87 percent and Python and PowerShell patching tools that improved consistency."]),
 ("L2/L3 Technical Support Engineer — Australia Post via Capgemini", "February 2026–June 2026 · Melbourne, Victoria", ["Delivered endpoint, infrastructure, and service-operations support, and created ServiceNow automation that removed hundreds of hours of repetitive work each month."])
 ],
 "systems": [
 ("Senior Managed Services Engineer — Capgemini, consultant to Department of Education Victoria", "December 2021–2023 · Melbourne, Victoria", ["Managed SharePoint Online, Exchange Online, Teams, Entra ID, hybrid identity, Azure, and Google Workspace for 660,000+ users.", "Led Tier-3 escalation, root-cause analysis, security-baseline work, identity synchronisation troubleshooting, and durable operational documentation."]),
 ("L2/L3 Technical Support Engineer — Australia Post via Capgemini", "February 2026–June 2026 · Melbourne, Victoria", ["Delivered Windows endpoint support, provisioning, imaging, access, inventory, and escalation coordination in a high-volume enterprise environment.", "Built ServiceNow automation that removed repetitive manual data entry while working within locked-down endpoint controls."]),
 ("Application Support Engineer — Knosys", "December 2020–December 2021 · Melbourne, Victoria", ["Resolved complex Windows Server, SQL, API, authentication, and application-platform issues and automated patching and migration activities."])
 ],
 "endpoint": [
 ("L2/L3 Technical Support Engineer — Australia Post via Capgemini", "February 2026–June 2026 · Melbourne, Victoria", ["Delivered L1/L2 endpoint support covering hardware diagnostics, Windows imaging, provisioning, loan devices, accessories, and user access.", "Managed Windows 10/11 migrations, standardised SOE builds, Autopilot/UEM enrolment, inventory, and compliant equipment disposal.", "Built ServiceNow automation and supported complex faults as an escalation point for L3 teams."]),
 ("Endpoint Migration Engineer — St John of God Health Care", "October 2025–January 2026 · Melbourne, Victoria", ["Led Windows 11 migration across more than 100 clinical endpoints using Autopilot, Intune, SOE controls, application validation, and hypercare.", "Managed hardware preparation, enrolment, policy application, compliance checks, user handover, and training in a live healthcare environment."]),
 ("Senior Managed Services Engineer — Capgemini, consultant to Department of Education Victoria", "December 2021–2023 · Melbourne, Victoria", ["Supported M365, identity, security, and service operations across a Victorian government environment supporting schools and administrative services."])
 ],
 "field": [
 ("Telecommunications Technician — National Broadband Network", "October 2016–November 2017 · Melbourne, Victoria", ["Executed fibre and copper structured-cabling deployments, site assessments, Layer 1 diagnostics, equipment installation, and customer communication across Melbourne."]),
 ("HVAC Service Technician — PolaAir", "2017 · Melbourne, Victoria", ["Installed, maintained, and repaired commercial HVAC equipment; diagnosed mechanical and electrical faults and managed multiple field-service jobs safely."]),
 ("L2/L3 Technical Support Engineer — Australia Post via Capgemini", "February 2026–June 2026 · Melbourne, Victoria", ["Managed physical endpoint lifecycle work, hardware diagnostics, inventory, break-fix support, and documented operational processes."])
 ],
 "local": [
 ("L2/L3 Technical Support Engineer — Australia Post via Capgemini", "February 2026–June 2026 · Melbourne, Victoria", ["Delivered high-volume, customer-facing support while coordinating hardware, accessories, loan assets, and accurate service records.", "Prioritised competing tasks, resolved issues calmly, and maintained clear communication with a wide range of end users."]),
 ("Telecommunications Technician — National Broadband Network", "October 2016–November 2017 · Melbourne, Victoria", ["Worked independently across Melbourne sites, managed customer communication, completed physical installation tasks, and maintained safe, reliable service standards."])
 ]
}

def resume(role):
    parts = [f"# Sam Ludwig\nMelbourne, VIC | 0405 993 245 | sam.ludwig@gmail.com\nsamludwig.au | github.com/Ludwixix\n\n## Target Role: {role['title']}\n\n### Professional Summary\n{role['summary']}\n\n### Profile\n{role['profile']}\n\n### Core Skills\n{role['skills']}\n\n### Professional Experience"]
    for title, dates, bullets in experience[role['focus']]:
        parts += [f"### {title}\n{dates}"] + [f"- {b}" for b in bullets] + [""]
    parts.append("### Selected Projects\n- ServiceNow workload tool — browser extension integrating Microsoft 365 presence data with ServiceNow queues to improve ticket allocation.\n- M365 diagnostic GUI — Python tool that helps L1 staff run repeatable PowerShell diagnostics against Exchange and Teams.\n\n### Qualifications\nAZ-104 Azure Administrator Associate · AZ-900 Azure Fundamentals · ITIL 4 Foundation · Certified Scrum Master · Diploma of Information Technology — Coder Academy\n\n### Work Rights\nAustralian citizen · unrestricted Australian work rights · available immediately\n")
    return "\n".join(parts)

def letter(role):
    key = ", ".join(role['terms'][:3]).lower()
    return dedent(f"""# Sam Ludwig
Melbourne, VIC | 0405 993 245 | sam.ludwig@gmail.com

**Re: {role['title']} — {role['company']}**

Dear Hiring Manager,

I’m applying for the {role['title']} position with {role['company']}. {role['profile']}

My recent experience combines hands-on service delivery with enterprise engineering. At Australia Post via Capgemini, I delivered endpoint and infrastructure support, managed hardware and software lifecycle work, resolved complex faults, and built ServiceNow automation that removed repetitive manual effort. At St John of God Health Care, I delivered a Windows 11 migration across more than 100 clinical endpoints using Autopilot, Intune, application validation, and post-deployment support.

Earlier work with Capgemini for the Department of Education Victoria involved Azure, Microsoft 365, Entra ID, hybrid identity, security-aware change, Tier-3 escalation, PowerShell automation, and documented operational improvement at significant scale. My field and application-support background adds practical fault-finding, customer communication, disciplined triage, and durable root-cause analysis.

The areas most relevant to the role are {key}. I’d bring dependable task ownership, clear communication, and a willingness to learn the way your team works.

I’m happy to confirm any licence, qualification, check, roster, or role-specific requirement before progressing.

Thank you for considering my application. I would welcome a conversation about how my background could contribute to your team.

Yours sincerely,
Sam Ludwig
""").strip()+"\n"

def email(role):
    terms = ", ".join(role['terms'][:3]).lower()
    return dedent(f"""# Opening Email — {role['title']}

**Company:** {role['company']}
**Location:** {role['location']}
**Application link:** {role['url']}

## Subject
Application — {role['title']} — Sam Ludwig

## Email body
Hello Hiring Manager,

I’m writing about the {role['title']} position with {role['company']}. {role['profile']}

My background includes enterprise technical support, infrastructure and endpoint delivery, systematic fault-finding, customer communication, process-focused documentation, and automation.

The areas most relevant to the role are {terms}.

I’d welcome a brief conversation about the role and any position-specific requirements.

Regards,
Sam Ludwig
0405 993 245
sam.ludwig@gmail.com
""").strip()+"\n"

for r in roles:
    base = f"{PREFIX}_{r['slug']}"
    (APP / f"{base}_resume.md").write_text(resume(r), encoding="utf-8")
    (APP / f"{base}_cover_letter.md").write_text(letter(r), encoding="utf-8")
    (APP / f"{base}_opening_email.md").write_text(email(r), encoding="utf-8")
    audit = {"audit_version":"1.0","fit":"Strong fit" if r["score"] >= 85 else "Adjacent fit — review carefully","score":r["score"],"source":"Indeed","source_url":r["url"],"application_route":r["url"],"application_route_type":"Indeed listing","listing_verification":"Individual listing captured from a non-LinkedIn source on 12 August 2026; confirm availability before applying.","matched_terms":r["terms"],"requested_terms":r["terms"],"unsupported_or_unverified_terms":r["gaps"],"requirements_to_confirm":["Confirm the listing is still open and review the exact job description."] + r["gaps"],"recommendation":"Review the listing and requirements before applying.","human_review":common_review,"source_basis":"Role title, listing metadata, search rationale, and verified candidate profile"}
    (AUDITS / f"{base}_audit.json").write_text(json.dumps(audit, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
print(f"Generated {len(roles)} application packs: {len(roles)*3} Markdown sources and {len(roles)} audit JSON files.")
